apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-coworking-pro3
  name: backend-coworking-pro3
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 5153
      targetPort: 5153
  selector:
    service: backend-coworking-pro3
